fixed script EOL indent error

diff --git a/usr/bin/dogiap b/usr/bin/dogiap
--- a/usr/bin/dogiap
+++ b/usr/bin/dogiap
@@ -224,31 +224,31 @@ main() {
         echo "> Creating GitHub Actions directory and file"  
         mkdir -p ./.github/workflows
         cat <<EOL > "$WorkflowFilePath"
-    name: Auto Update -> $RepoName
+name: Auto Update -> $RepoName
 
-    on:
-    push:
-        branches:
-        - main
+on:
+push:
+    branches:
+    - main
 
-    jobs:
-    restart-$RepoName:
-        runs-on: ubuntu-latest
-        steps:
-        - name: Checkout to the branch
-            uses: actions/checkout@v2
+jobs:
+restart-$RepoName:
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout to the branch
+        uses: actions/checkout@v2
 
-        - name: Send POST request to restart $RepoName
-            run: |
-            curl_response=\$(curl -X POST "$WebHookServerUrl" -H "Content-Type: application/json" -H "X-GitHub-Event: push" --data '{"ContainerName": "$RepoName"}' --fail --silent --show-error)
+    - name: Send POST request to restart $RepoName
+        run: |
+        curl_response=\$(curl -X POST "$WebHookServerUrl" -H "Content-Type: application/json" -H "X-GitHub-Event: push" --data '{"ContainerName": "$RepoName"}' --fail --silent --show-error)
 
-            if [ \$? -ne 0 ]; then
-                echo "> Failed to send webhook request"
-                exit 1
-            fi
+        if [ \$? -ne 0 ]; then
+            echo "> Failed to send webhook request"
+            exit 1
+        fi
 
-            echo "> Webhook request sent successfully. Response: \$curl_response"
-            exit 0
+        echo "> Webhook request sent successfully. Response: \$curl_response"
+        exit 0
 EOL
         print_status "Creating GitHub Actions directory and file" "success"
     fi
